### ISSUE TITLE
tab bar positioning

### ISSUE THREAD

**Issue by djdance** [scihant/CTShowcase#15]
1. a message covers circle, doesn't properly auto positioned.
2. how to get UITabBarItem? the code below works, but looks hacky.

`let b:UIView = self.thirdTabButton.value(forKey: "view") as! UIView`

![screen shot 2018-01-28 at 14 46 15_cr](https://user-images.githubusercontent.com/2269720/35481725-62ff0bd8-043a-11e8-841e-fb03cdc360a1.jpg)

**Comment by scihant** [comment]
(1) is caused by the overly simplistic positioning logic. I'll update it to work properly in cases like this whenever I find the time. thanks for reporting it.

(2) isn't really a hack. It's the most viable way to get a view from a tabbar item.
