### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ecnepsnai** [scihant/CTShowcase#2]
Any plans on updating to Swift 3 or is this project abandoned?

**Comment by scihant** [comment]
No, it's not abandoned. I'm planning to update it very soon. This has served me as a reminder, so thanks for that.

**Comment by scihant** [comment]
I've just updated the code to use Swift 3

**Comment by ecnepsnai** [comment]
Can you please sync the pod with trunk? Still only shows version 1.0 on Cocoapods https://cocoapods.org/?q=CTShowcase

**Comment by scihant** [comment]
Done. The update should be reflected there soon.
