### ISSUE TITLE
Terminating app - Key Value Observer *ERROR*

### ISSUE THREAD

**Issue by n1tesh** [scihant/CTShowcase#7]
In my TabBarController

    let showCase = CTShowcaseView(title: "Title" message: "Message", key: nil){ ()

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let tabBarViews = self.orderedTabBarItemViews()
        showCase.setup(for: tabBarViews[2], offset: CGPoint.zero, margin: 5)
        showCase.show()
    }

After I Log out, I get this error 

> 2017-03-14 15:51:09.606694 Drabble[696:102182] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x101b5f740 of class UITabBarButton was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x17022aa60> (
> <NSKeyValueObservance 0x170256650: Observer: 0x101b5b020, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170256680>
> 

This is happening as after Logout I redirects user to my RootViewController which does not have TabBarController.

**Comment by scihant** [comment]
You should dismiss the showcase and set it to nil before the TabBar gets released (before you redirect the user) to make sure that it gets deallocated before the TabBar does. Otherwise it will try to observe the changes to a deallocated instance and you'll get that error.

**Comment by n1tesh** [comment]
Did that then I got this error

`017-03-15 11:02:51.855265 Drabble[282:11824] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <Drabble.CTShowcaseView 0x10de61490> for the key path "frame" from <UITabBarButton 0x10dd71930> because it is not registered as an observer.'`

**Comment by scihant** [comment]
Can you send me an example project that reproduces the issue

**Comment by n1tesh** [comment]
How do you dismiss the showcase ?
I'll create new example project send it if this is not solved.

**Comment by scihant** [comment]
It should be dismissed when the user taps anywhere on the screen while the showcase is visible.

I've just realized that there is no way to programmatically dismiss the showcase because the dismiss() method is marked as private.  I've just made it public in the development branch.
