### ISSUE TITLE
Swift 3 subclass

### ISSUE THREAD

**Issue by ghost** [scihant/CTShowcase#8]
In Swift 3 was introduced a new tag to give the possibility to subclass outside the module, can you please change the implementation from public to open? I need to subclass CTShowcaseView in order to add a better handler for touch recognise, so I can intercept where you touch and call a segue if necessary, instead of simply dismiss the view. Thanks

**Comment by scihant** [comment]
Fixed with the 2.1.1 release

**Comment by RajaReddyiOS** [comment]
how to highlight certain region using CTShowcase

**Comment by scihant** [comment]
Please read the readme file to learn how to use the library.
